import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    message: "Chat API is working",
    status: "ready",
    timestamp: new Date().toISOString(),
    instructions: "Use POST /api/chat with a prompt to get AI responses"
  });
}

export async function POST(req) {
  try {
    const { prompt } = await req.json();
    
    if (!prompt) {
      return NextResponse.json(
        { error: "Please provide a prompt" },
        { status: 400 }
      );
    }

    // Mock response for testing
    const mockResponse = `This is a test response to: "${prompt}". In a real implementation, this would be generated by Gemini AI.`;

    return NextResponse.json({
      response: mockResponse,
      timestamp: new Date().toISOString(),
      mode: "test"
    });

  } catch (error) {
    return NextResponse.json(
      { error: "Test API error" },
      { status: 500 }
    );
  }
}
